import "./globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav className="color3 w-full h-[60px] flex items-center text-white font-bold text-color4 text-3xl p-2">
          Country Stats
        </nav>
        {children}
      </body>
    </html>
  );
}
